### ISSUE TITLE
Wrong text domain used for "There was an error processing your payment." message

### ISSUE THREAD

**Issue by Crabcyborg** [Strategy11/formidable-payments#15]
https://github.com/Strategy11/formidable-payments/blob/01c1f958537d8bd076871b73763da48c045a5bc7/controllers/FrmTransActionsController.php#L127

Should be `formidable-payments`.

**Comment by Crabcyborg** [comment]
@stephywells adding phpcs, it caught a lot of these references to the `frmauthnet` text domain inside of the `formidable-payments` portion of this code.

I'm wondering if I should add an exception for that, so `frmauthnet` is an allowed text domain in this add on, or to just set all of these to use the standard `formidable-payments` domain instead. What do you think?

https://github.com/Strategy11/formidable-payments/blob/01c1f958537d8bd076871b73763da48c045a5bc7/models/FrmTransAction.php#L218

https://github.com/Strategy11/formidable-payments/blob/01c1f958537d8bd076871b73763da48c045a5bc7/models/FrmTransAction.php#L238

https://github.com/Strategy11/formidable-payments/blob/01c1f958537d8bd076871b73763da48c045a5bc7/views/action-settings/options.php#L119

https://github.com/Strategy11/formidable-payments/blob/01c1f958537d8bd076871b73763da48c045a5bc7/views/action-settings/options.php#L125

**Comment by stephywells** [comment]
I think we should use the formidable-payments domain here since this is used in Stripe too. I think this was a copy/paste that didn't get changed.
